Afegir selector any al pujar apunts
data-students/apunts-dades-old pull request #71
Opened 2024-03-15 18:53 UTC by marcfranquesa

Primera PR amb pes, fúnenme

2024-03-15 18:56 UTC, marcfranquesa commented
mmm maybe estaria bé tenir-ho 2021/2022 en comptes de 2021

2024-03-16 16:04 UTC, PauMatas requested changes
La resta lgtm

2024-03-16 16:04 UTC, PauMatas commented on src/app/[slug]/submit/page.tsx
> +        session={session}
no crec que sigui bona pràctica passar la sessió com a paràmetre, per a anar bé jo faria el getAuthSession a la component Form de components/Form.tsx. No t'hauria de donar problemes perquè Form.tsx ja és client side (es pot saber per el "use client" sorry per el mansplaining si ja ho sabies).

2024-03-16 16:04 UTC, PauMatas commented on src/components/Form.tsx
> +  const begin = session ? Number(session.user.generacio) : 2017 // primera promoció
En la línia de l'altre comentari, si tinguessis problemes accedint a la sessio des d'aquesta component pots o passar com a paràmetre el session.user.generacio o simplement donar l'opció de tots els anys.

2024-03-16 18:42 UTC, marcfranquesa commented on src/app/[slug]/submit/page.tsx
> +        session={session}
no se ni que es client side la vd ara canvio

2024-03-16 18:50 UTC, marcfranquesa commented on src/app/[slug]/submit/page.tsx
> +        session={session}
<img width="748" alt="image" src="https://github.com/data-students/apunts-dades/assets/110655741/76a6b9d3-549c-4b7b-88fb-7b7121d1916c">

amb el canvi

2024-03-16 19:28 UTC, PauMatas approved these changes
Perfecte!

En algun moment hauriem de mirar de fer que onChange del selector d'assignatura canvii l'any però m'ho he mirat per sobre i fa una mica de pal. Per altra banda estaria bé ficar els dropdowns un al costat de l'altre aixi ens queda un forms mes compacte pero de nou això ja serà una altra PR.

Bona canço btw 👷🏼‍♀️🏗️

2024-03-16 19:40 UTC, merged