1 scrolling combobox
data-students/apunts-dades-old pull request #72
Opened 2024-03-16 18:51 UTC by PauMatas

![image](https://github.com/data-students/apunts-dades/assets/61761147/4a784679-01c6-4471-9b29-70674dbaef95)

2024-03-16 20:36 UTC, puigde requested changes

2024-03-16 20:36 UTC, puigde commented on src/components/Form.tsx
> +
API call vs. posar-ho en un JSON? 

Les assignatures canvien poc com per haver de fer una crida aquí

2024-03-16 20:36 UTC, puigde commented on src/components/Form.tsx
> +
++ hi ha conflicts amb main

2024-03-16 20:36 UTC, puigde commented on src/components/Combobox.tsx
> +        <PopoverContent className="max-h-80 flex flex-col w-80 p-0">
Molt nice!!

2024-03-16 20:36 UTC, puigde commented on src/components/Form.tsx
> +
mmmmmmmmm bueno veig que amb l'empty array només corre després del primer render del component així que potser no és tan greu, has provat si al interactuar-hi es nota alguna diferència @PauMatas sinó podem tirar-ho endavant quan els conflicts estiguin resolts.

2024-03-17 08:53 UTC, PauMatas commented on src/components/Form.tsx
> +
Em justifico, vaig pensar que valia la pena no tenir-ho hardcodejat i que ho podiem mirar de treure de la BD. Quan vaig fer la crida a BD des de Form.tsx a més de tenir problemes d'async, await, useEffect, etc... em deia que no podia fer una crida a BD des d'una component client side. Per això vaig recorrer a fer una crida a la API. Estic d'acord que canvien poc, si penses que ha de ser més eficient o millor per l'experiència d'usuari posem directament el JSON en un fitxer json o a src/config.js i llestos.
A la pregunta de si al interactuar-hi hi ha diferència et diria que si tal i com carrega la pàgina obres el dropdown et surt buit, s'omple de valors als ~2s. Si no us sembla suficient podem fer la solució del JSON que he comentat abans o posar-hi un [Skeleton](https://ui.shadcn.com/docs/components/skeleton) (que a mi em sembla mooooolt clean).
Main solventat!

2024-03-17 09:08 UTC, PauMatas commented on src/components/Form.tsx
> +
Rectifico, skeleton no és viable i en dev el temps sense assignatures és <1s

2024-03-18 09:04 UTC, puigde commented
Ho acabo de testejar a la preview i ni es nota. Ho podem tirar endavant no és gens greu. Boníssim push @PauMatas 🚀🚀

2024-03-18 09:04 UTC, puigde approved these changes

2024-03-18 09:04 UTC, merged